config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "pricehists/index"
  root 'pricehists#index'
  resources :pricehists do
    collection {get "check"}
    collection {get "find"}
    collection {get "detail"}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/digital_item.rb
class DigitalItem < ApplicationRecord

  def self.check(date, maker, startprice, endprice, type, keyword)

    if type == "all" and keyword == "" then
      rel = where("itemid LIKE ? and maker = ? and price between ? and ?","#{date}%", "#{maker}", "#{startprice}", "#{endprice}")
    else
      rel = where("itemid LIKE ? and maker = ? and price between ? and ? and itype = ?","#{date}%", "#{maker}", "#{startprice}", "#{endprice}", "#{type}")
    end

  end

  def self.makercount(date)
    rel = where("itemid LIKE ?","#{date}%").group(:maker).order("count_maker DESC").count(:maker)
  end

end

app/models/summary_item.rb
class SummaryItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pricehists_controller.rb
class PricehistsController < ApplicationController

  def index
    if params[:item_category] == nil then
      @Summary=SummaryItem.group(:itemdate).sum(:count)
      @Title="Total Summary"
    end

    if params[:item_category] == "dg" then
      @Summary=SummaryItem.where(category: params[:item_category]).group(:itemdate).sum(:count)
      @Title="Digital Summary"
    end

    if params[:item_category] == "ef" then
      @Summary=SummaryItem.where(category: params[:item_category]).group(:itemdate).sum(:count)
      @Title="Effector Summary"
    end

    if params[:item_category] == "am" then
      @Summary=SummaryItem.where(category: params[:item_category]).group(:itemdate).sum(:count)
      @Title="Amp Summary"
    end

  end

  def show
    @item=DigitalItem.find(params[:id])
  end

  def find
    @makers=DigitalItem.select(:maker).distinct.order(:maker)
  end

  def check
    @checkdate=params[:q].to_date.strftime('%Y/%m/%d')
    @checkmaker=params[:m]
    startprice, endprice, @rangeprice =calc(params[:p])
    @pricehists=DigitalItem.paginate(page: params[:page], per_page: 40).check(params[:q], params[:m], startprice, endprice, params[:ty], params[:key])

  end

  def detail
    @checkdate=params[:item_date].gsub("-","/")
    @makercount=DigitalItem.makercount(params[:item_date].delete("-"))
  end

  private
    def calc(price)
      if price.to_i == 100000 then
        startprice = 0
        endprice = 100000
        rangeprice = " 〜 ¥100,000"
      elsif price.to_i > 500000 then
        startprice = 500000
        endprice = 100000000
        rangeprice = "¥500,000  〜 "
      elsif price == "ALL"
        startprice = 0
        endprice = 100000000
        rangeprice = "すべて"
      else
        startprice = price.to_i - 200000
        endprice = price.to_i
        rangeprice = "¥" + startprice.to_s(:delimited) + " 〜 ¥" + endprice.to_s(:delimited)
      end
      return startprice,  endprice, rangeprice
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pricehists_helper.rb
module PricehistsHelper
end

app/views/digitalitems/check.html.erb
<div class="pagination pagination-sm">
  <p class="text-secondary">
    <%= will_paginate @digitalitems, renderer: WillPaginate::ActionView::BootstrapLinkRenderer,:inner_window => 1 %>
  </p>
</div>

<div class="text-black text-center py-2">
  <h5 class="text-secondary">検索結果 <%= @digitalitems.count %>件</h5>
</div>
<div class="text-black text-center py-1">
  <h6 class="text-secondary">日付：<%= @checkdate %> メーカー：<%= @checkmaker %>　価格帯：<%= @rangeprice %></h6>
</div>
<div class="table-responsive">
  <table class="table table-hover table-sm ">
    <thead class="table-light text-info">
      <tr>
        <th>メーカー</th>
        <th>モデル</th>
        <th>プライス</th>
      </tr>
    </thead>
    <% @digitalitems.each do |item| %>
    <tbody>
      <tr>
        <td class="text-secondary"><%= item.maker %></td>
        <td><%= link_to item.name, digitalitem_path(item), :target=>["_blank"] %></td>
        <td class="text-secondary"><%= "¥" + item.price.to_s(:delimited) %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

<div class="pagination pagination-sm">
  <%= will_paginate @digitalitems, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, :inner_window => 1 %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      <%= link_to "楽器 Price Hist", pricehists_path, {:class => "text-secondary"} %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "about",   '#', {:class => "text-secondary"} %></li>
      <li><%= link_to "contact", '#', {:class => "text-secondary"} %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background:#9BF; height:50px;">
    <%= link_to "楽器 Price Hist", pricehists_path, {:class => "navbar-brand"} %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#nav1">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav1">
      <ul class="navbar-nav">
        <li class="nav-item active"><%= link_to "Total", pricehists_path, {:class => "nav-link text-secondary"} %></li>
        <li class="nav-item"><%= link_to "Digital", pricehists_path(:item_category => "dg"), {:class => "nav-link text-secondary"} %></li>
        <li class="nav-item"><%= link_to "Effector", pricehists_path(:item_category => "ef"), {:class => "nav-link text-secondary"} %></li>
        <li class="nav-item"><%= link_to "Amp", pricehists_path(:item_category => "am"), {:class => "nav-link text-secondary"} %></li>
      </ul>
      <hr class="d-md-none border-secondary my-2">
      <form class="form-inline ml-auto">
        <label class="sr-only" for="kw">検索キーワード</label>
        <input type="search" class="form-control form-control-sm mr-sm-2 my-2 my-md-0" placeholder="キーワード" id="kw">
        <button type="submit" class="btn btn-info btn-sm my-2 my-md-0">検索</button>
      </form>
    </div>
  </nav>

  <!-- <div class="jumbotron text-white" style="background:url(P6_20180716.jpg);background-size:cover;text-shadow: 2px 2px 4px #666; height:60px;">
    <h2 class="mb-1">楽器 Price Hist</h2>
    <p>Happy people make happy food.</p>
  </div> -->

app/views/layouts/_retrieving.html.erb
<%= form_tag(:check_pricehists, method: "get") do %>

<div class="py-2 row">
  <label class="col-sm-2 col-form-label">日付</label>
  <div class="col-sm-10">
    <%= select_tag(:q, options_for_select({'2018年10月05日' => 20181005, '2018年10月06日' => 20181006}), {:class => "form-control"}) %>
  </div>
</div>

<div class="py-2 row">
  <label class="col-sm-2 col-form-label">メーカー</label>
  <div class="col-sm-10">
    <%= select_tag(:m, options_from_collection_for_select(@makers, :maker, :maker, "ROLAND"), {:class => "form-control"}) %>
  </div>
</div>

<div class="py-2 row">
  <label class="col-sm-2 col-form-label">価格帯</label>
  <div class="col-sm-10">
    <%= select_tag(:p, options_for_select([['〜 ¥100,000', 100000],['¥100,000 〜 ¥300,000', 300000],
        ['¥300,000 〜 ¥500,000', 500000],['¥500,000 〜 ', 500001],['すべての価格帯', "ALL"]]), {:class => "form-control"}) %>
  </div>
</div>


<div class="row py-2">
  <label class="col-sm-2 col-form-label">新品・中古</label>
  <div class="col-sm-10">
    <%= radio_button_tag(:ty, value = "all", checked = true, options = {}) %>
    <%= label_tag :tyl, 'すべて' %>
    <%= radio_button_tag(:ty, value = "new", checked = false, options = {}) %>
    <%= label_tag :tyl, '新品' %>
    <%= radio_button_tag(:ty, value = "old", checked = false, options = {}) %>
    <%= label_tag :tyl, '中古' %>
  </div>
</div>

<div class="row py-1">
  <label class="col-sm-2 col-form-label">品名キーワード</label>
  <div class="col-sm-10">
    <%= search_field_tag(:key, "", options = {:class => "form-control"}) %>
  </div>
</div>

<div class="row py-1">
  <label class="col-sm-2 col-form-label">並び順</label>
  <div class="col-sm-10">
    <label><%= check_box_tag(:cbm, "1", checked = false, options = {:class => "form-control"}) %> <%= label_tag :cbm, "メーカー" %></label>
    <label><%= check_box_tag(:cbp, "1", checked = true, options = {:class => "form-control"}) %> <%= label_tag :cbp, "価格" %></label>
  </div>
</div>

<div class="py-3">
  <button class="btn btn-info" type="submit" >Check</button>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PriceHist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body style="padding-top:4rem">
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pricehists/bk_index.html.erb
<div class="col-10 row">
  <div class="col-3"></div>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link text-secondary active" id="digital-tab" data-toggle="tab" href="#Digital" role="tab" aria-controls="home" aria-selected="true">Digital</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-secondary" id="guitar-tab" data-toggle="tab" href="#Guitar" role="tab" aria-controls="profile" aria-selected="false">Guitar</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-secondary" id="effector-tab" data-toggle="tab" href="#Effector" role="tab" aria-controls="contact" aria-selected="false">Effector</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-secondary" id="effector-tab" data-toggle="tab" href="#..." role="tab" aria-controls="contact" aria-selected="false">...</a>
    </li>
  </ul>
</div>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active py-2" id="digital" role="tabpanel" aria-labelledby="digital-tab">
    <%= render 'layouts/retrieving' %>
  </div>
  <div class="tab-pane fade" id="guitar" role="tabpanel" aria-labelledby="guitar-tab">
    <%= render 'layouts/retrieving' %>
  </div>
  <div class="tab-pane fade" id="effector" role="tabpanel" aria-labelledby="effector-tab">
    <%= render 'layouts/retrieving' %>
  </div>
</div>

app/views/pricehists/check.html.erb
<div class="pagination pagination-sm">
  <p class="text-secondary">
    <%= will_paginate @pricehists, renderer: WillPaginate::ActionView::BootstrapLinkRenderer,:inner_window => 1 %>
  </p>
</div>

<div class="text-black text-center py-2">
  <h5 class="text-secondary">検索結果 <%= @pricehists.count %>件</h5>
</div>
<div class="text-black text-center py-1">
  <h6 class="text-secondary">
    日付：<%= @checkdate %> メーカー：<%= @checkmaker %>　価格帯：<%= @rangeprice %>
  </h6>
</div>
<% if @pricehists.count > 0 %>
<div class="table-responsive">
  <table class="table table-hover table-sm ">
    <thead class="table-light text-info">
      <tr>
        <th>メーカー</th>
        <th>モデル</th>
        <th>プライス</th>
      </tr>
    </thead>
    <% @pricehists.each do |item| %>
    <tbody>
      <tr>
        <td class="text-secondary"><%= item.maker %></td>
        <td><%= link_to item.name, pricehist_path(item), :target=>["_blank"] %></td>
        <td class="text-secondary"><%= number_to_currency(item.price, :locale => 'jp') %></td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>
<% else %>
  <div class="text-center">
    <p class="text-primary"><%= link_to "検索画面へ戻る", pricehists_path %></p>
  </div>
<% end %>

<div class="pagination pagination-sm">
  <%= will_paginate @pricehists, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, :inner_window => 1 %>
</div>

app/views/pricehists/detail.html.erb
<h4 class="text-center text-secondary my-3">
  <%= @checkdate %> メーカ別件数
</h4>
<div class="col-12 d-flex flex-wrap justify-content-between">
  <% @makercount.each do |maker, count| %>
    <% if count > 0 %>
      <%= link_to detail_pricehists_path, class: 'btn btn-primary my-1 py-2' do %>
        <%= maker %> <%= content_tag :span, count, class: 'badge badge-danger' %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/pricehists/find.html.erb
<%= form_tag(:check_pricehists, method: "get") do %>

<div class="py-2 row">
  <div class="col-3" style="background: #f5fffa"></div>
  <label class="col-2 col-form-label">日付</label>
  <div class="col-4">
    <%= select_tag(:q, options_for_select({'2018年10月05日' => 20181005, '2018年10月06日' => 20181006}), {:class => "form-control"}) %>
  </div>
</div>

<div class="py-2 row">
  <div class="col-3"></div>
  <label class="col-2 col-form-label">メーカー</label>
  <div class="col-4">
    <%= select_tag(:m, options_from_collection_for_select(@makers, :maker, :maker, "ROLAND"), {:class => "form-control"}) %>
  </div>
</div>

<div class="py-2 row">
  <div class="col-3"></div>
  <label class="col-2 col-form-label">価格帯</label>
  <div class="col-4">
    <%= select_tag(:p, options_for_select([['〜 ¥100,000', 100000],['¥100,000 〜 ¥300,000', 300000],
        ['¥300,000 〜 ¥500,000', 500000],['¥500,000 〜 ', 500001],['すべての価格帯', "ALL"]]), {:class => "form-control"}) %>
  </div>
</div>


<div class="row py-2">
  <div class="col-3"></div>
  <label class="col-2 col-form-label">新品・中古</label>
  <div class="col-4">
    <%= radio_button_tag(:ty, value = "all", checked = true, options = {}) %>
    <%= label_tag :tyl, 'すべて' %>
    <%= radio_button_tag(:ty, value = "new", checked = false, options = {}) %>
    <%= label_tag :tyl, '新品' %>
    <%= radio_button_tag(:ty, value = "old", checked = false, options = {}) %>
    <%= label_tag :tyl, '中古' %>
  </div>
</div>

<div class="row py-1">
  <div class="col-3"></div>
  <label class="col-2 col-form-label">品名キーワード</label>
  <div class="col-4">
    <%= search_field_tag(:key, "", options = {:class => "form-control"}) %>
  </div>
</div>

<div class="row">
  <div class="col-3"></div>
  <label class="col-2 col-form-label">並び順</label>
  <div class="col-4">
    <%= check_box_tag(:cbm, "1", checked = false, options = {}) %>
    <%= label_tag :cbm, "メーカー" %>
    <%= check_box_tag(:cbp, "1", checked = true, options = {}) %>
    <%= label_tag :cbp, "価格" %>
  </div>
</div>

<div class="row">
  <div class="col-3"></div>
  <div class="py-3 col-6">
    <button class="btn btn-info btn-block" type="submit" >Check</button>
  </div>
</div>

<% end %>

app/views/pricehists/index.html.erb
<h4 class="text-center text-secondary"><%= @Title %></h4>
<%= month_calendar do |date| %>
  <% @Summary.each do |itemsdate, itemscount| %>
    <% if date == itemsdate.to_date %>
      <%= link_to detail_pricehists_path(:item_date => itemsdate.to_date), class: 'btn btn-info' do %>
        <%= itemsdate[4,2] + "/" + itemsdate[6,2] %> <%= content_tag :span, itemscount, class: 'badge badge-danger' %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/pricehists/show.html.erb
<table>
  <% if File.exist? "#{Rails.root}/app/assets/images/#{@item.code}_s.jpg" %>
    <tr><td><%= image_tag(@item.code + "_s.jpg", :width => '120') %></td></tr>
  <% else %>
    <tr><h6>画像なし</h6></tr>
  <% end %>
  <tr><td><%= @item.maker %></td></tr>
  <tr><td><%= @item.name %></td></tr>
  <tr><td><%= "¥" + @item.price.to_s(:delimited) %></td></tr>
</table>